# Generated by Django 4.2.30 on 2026-05-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='restaurents',
            new_name='restaurants',
        ),
    ]
