# Generated by Django 4.2.30 on 2026-05-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0002_rename_restaurents_employee_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurentowner',
            old_name='restaurents',
            new_name='restaurants',
        ),
    ]
